name: Master Branch Checks
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Compile
        run: cargo build
      - name: Check formatting
        run: cargo fmt -- --check
      - name: Run tests
        run: cargo test
      - name: Make sure documentation builds
        run: cargo doc --no-deps
